create database exam_qans1;
use exam_qans1;
CREATE TABLE exam_questions (
    question_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    multiple_questions TEXT NOT NULL,
    answers VARCHAR(500) NOT NULL
);
INSERT INTO exam_questions (multiple_questions, answers) VALUES
('1. What does CMA stand for? A) Certified Market Analyst B) Certified Management Accountant C) Certified Money Accountant D) Corporate Management Analyst', 'B'),
('2. Which organization conducts the US CMA exam? A) AICPA B) IMA C) ACCA D) CFA Institute', 'B'),
('3. How many parts are there in the US CMA exam? A) 1 B) 2 C) 3 D) 4', 'B'),
('4. Which topic is included in CMA Part 1? A) Taxation B) Financial Planning C) Auditing D) Economics', 'B'),
('5. Which topic is covered in CMA Part 2? A) Strategic Financial Management B) Payroll Accounting C) Banking D) Insurance', 'A'),
('6. What is the formula for working capital? A) Assets - Equity B) Current Assets - Current Liabilities C) Revenue - Expenses D) Sales - Costs', 'B'),
('7. Which financial statement shows company profitability? A) Balance Sheet B) Cash Flow Statement C) Income Statement D) Trial Balance', 'C'),
('8. Which costing method includes fixed and variable manufacturing costs? A) Marginal Costing B) Standard Costing C) Absorption Costing D) Opportunity Costing', 'C'),
('9. What is ROI? A) Return on Investment B) Rate of Interest C) Revenue on Income D) Return on Inventory', 'A'),
('10. Which budget starts from zero every period? A) Flexible Budget B) Cash Budget C) Master Budget D) Zero Based Budget', 'D'),
('11. What is the break-even point? A) Profit equals sales B) Revenue equals expenses C) Assets equal liabilities D) Cash inflow equals outflow', 'B'),
('12. Which ratio measures short-term liquidity? A) Debt Ratio B) Profit Margin C) Current Ratio D) ROI', 'C'),
('13. What is depreciation? A) Increase in asset value B) Allocation of asset cost C) Cash inflow D) Inventory reduction', 'B'),
('14. Which method gives equal yearly depreciation? A) Reducing Balance B) Straight Line C) Units Produced D) Double Declining', 'B'),
('15. Which cost changes with production volume? A) Fixed Cost B) Sunk Cost C) Variable Cost D) Opportunity Cost', 'C'),
('16. Which cost remains constant regardless of production? A) Variable Cost B) Fixed Cost C) Marginal Cost D) Prime Cost', 'B'),
('17. What does ERP stand for? A) Enterprise Resource Planning B) Economic Resource Plan C) Employee Resource Process D) External Revenue Plan', 'A'),
('18. Which statement shows assets liabilities and equity? A) Income Statement B) Balance Sheet C) Cash Budget D) Expense Report', 'B'),
('19. What is contribution margin? A) Sales - Fixed Costs B) Sales - Variable Costs C) Profit - Tax D) Revenue - Assets', 'B'),
('20. Which analysis compares actual results with budgeted results? A) Trend Analysis B) Ratio Analysis C) Variance Analysis D) SWOT Analysis', 'C'),
('21. What is a favorable variance? A) Actual costs exceed budget B) Revenue lower than budget C) Actual results better than expected D) Expenses increase', 'C'),
('22. Which accounting focuses on internal management decisions? A) Financial Accounting B) Cost Accounting C) Managerial Accounting D) Tax Accounting', 'C'),
('23. Which accounting is mainly for external users? A) Managerial Accounting B) Financial Accounting C) Cost Accounting D) Responsibility Accounting', 'B'),
('24. What is NPV? A) Net Present Value B) Net Profit Variance C) New Price Value D) Net Planning Volume', 'A'),
('25. What does IRR stand for? A) Internal Revenue Rate B) Internal Rate of Return C) Investment Return Ratio D) Interest Revenue Rate', 'B'),
('26. What is the payback period? A) Time to recover investment B) Time to pay salary C) Loan repayment interest D) Tax payment period', 'A'),
('27. What is internal control? A) Marketing process B) Employee training C) Process to safeguard assets D) Budget preparation', 'C'),
('28. Which term means dividing responsibilities to reduce fraud? A) Decentralization B) Segregation of Duties C) Benchmarking D) Standardization', 'B'),
('29. Which ratio measures profitability? A) Gross Profit Margin B) Current Ratio C) Debt Ratio D) Quick Ratio', 'A'),
('30. What is liquidity? A) Profit generation B) Ability to pay short-term debts C) Long-term investment D) Cost reduction', 'B'),
('31. Which budgeting method adjusts for activity levels? A) Fixed Budget B) Flexible Budget C) Zero Budget D) Cash Budget', 'B'),
('32. What is a KPI? A) Key Performance Indicator B) Known Profit Index C) Key Process Information D) Knowledge Planning Indicator', 'A'),
('33. Which analysis studies effect of assumption changes? A) Ratio Analysis B) Trend Analysis C) Sensitivity Analysis D) Variance Analysis', 'C'),
('34. What is benchmarking? A) Forecasting revenue B) Comparing with best practices C) Cost allocation D) Budget creation', 'B'),
('35. Which inventory system minimizes stock holding? A) FIFO B) LIFO C) JIT D) Weighted Average', 'C'),
('36. What does JIT stand for? A) Joint Inventory Tracking B) Just In Time C) Job Income Tax D) Justified Inventory Technique', 'B'),
('37. Which costing allocates costs based on activities? A) Standard Costing B) Activity Based Costing C) Marginal Costing D) Process Costing', 'B'),
('38. What is a cost driver? A) Employee B) Salesperson C) Factor causing cost changes D) Machine operator', 'C'),
('39. Which financial statement reports cash inflows and outflows? A) Income Statement B) Balance Sheet C) Cash Flow Statement D) Trial Balance', 'C'),
('40. What is goodwill? A) Cash reserve B) Company reputation value C) Inventory gain D) Tax refund', 'B'),
('41. What is amortization? A) Asset sale B) Intangible asset cost allocation C) Loan approval D) Revenue increase', 'B'),
('42. Which accounting method records transactions when incurred? A) Cash Accounting B) Accrual Accounting C) Fund Accounting D) Tax Accounting', 'B'),
('43. Which accounting method records transactions when cash changes hands? A) Accrual Accounting B) Responsibility Accounting C) Cash Accounting D) Standard Accounting', 'C'),
('44. What is a sunk cost? A) Future cost B) Recoverable cost C) Past irrecoverable cost D) Variable cost', 'C'),
('45. What is opportunity cost? A) Accounting error B) Lost benefit from alternative choice C) Fixed expense D) Tax liability', 'B'),
('46. Which ratio measures ability to pay immediate liabilities? A) Debt Ratio B) Quick Ratio C) ROI D) Gross Margin', 'B'),
('47. What is the formula for current ratio? A) Assets / Equity B) Current Assets / Current Liabilities C) Revenue / Expenses D) Profit / Sales', 'B'),
('48. Which type of cost is directly traceable to a product? A) Indirect Cost B) Fixed Cost C) Direct Cost D) Opportunity Cost', 'C'),
('49. Which term means authority delegated to lower levels? A) Centralization B) Decentralization C) Standardization D) Regulation', 'B'),
('50. Which process evaluates long-term investments? A) Budgeting B) Capital Budgeting C) Forecasting D) Auditing', 'B'),
('51. What is ethics in business? A) Advertising policy B) Moral principles C) Revenue planning D) Tax management', 'B'),
('52. Which term means intentional deception for gain? A) Audit B) Fraud C) Budgeting D) Forecasting', 'B'),
('53. What is inventory turnover? A) Sales / Assets B) COGS / Average Inventory C) Revenue / Inventory D) Profit / Inventory', 'B'),
('54. Which method assumes oldest inventory sold first? A) FIFO B) LIFO C) Weighted Average D) JIT', 'A'),
('55. Which method assumes newest inventory sold first? A) FIFO B) LIFO C) ABC D) JIT', 'B'),
('56. What is solvency? A) Short-term payment ability B) Long-term financial stability C) Revenue growth D) Inventory control', 'B'),
('57. Which budget combines all individual budgets? A) Flexible Budget B) Master Budget C) Cash Budget D) Sales Budget', 'B'),
('58. What is overhead cost? A) Direct labor cost B) Indirect manufacturing cost C) Prime cost D) Selling price', 'B'),
('59. Which cost includes direct material and direct labor? A) Prime Cost B) Conversion Cost C) Opportunity Cost D) Sunk Cost', 'A'),
('60. Which term refers to sales minus cost of goods sold? A) Net Income B) Gross Profit C) Operating Income D) Contribution Margin', 'B'),
('61. What is retained earnings? A) Company cash B) Accumulated profits C) Fixed assets D) Inventory value', 'B'),
('62. Which ratio measures debt proportion in assets? A) Debt Ratio B) Current Ratio C) Quick Ratio D) ROI', 'A'),
('63. Which financial activity manages company cash? A) Treasury Management B) Marketing C) Auditing D) Forecasting', 'A'),
('64. What is hedging? A) Increasing sales B) Reducing financial risk C) Hiring employees D) Budgeting expenses', 'B'),
('65. Which risk arises from currency fluctuations? A) Credit Risk B) Market Risk C) Foreign Exchange Risk D) Operational Risk', 'C'),
('66. What is inflation? A) Price decrease B) Increase in general prices C) Lower interest rates D) Lower wages', 'B'),
('67. What is deflation? A) Increase in demand B) Price decrease C) Tax increase D) Higher inflation', 'B'),
('68. Which scorecard measures organizational performance? A) Financial Scorecard B) Balanced Scorecard C) Risk Card D) Audit Card', 'B'),
('69. What is corporate governance? A) Tax regulation B) Company direction and control system C) Marketing strategy D) Employee policy', 'B'),
('70. Which analysis evaluates possible future situations? A) Scenario Analysis B) Ratio Analysis C) Trend Analysis D) Audit Analysis', 'A'),
('71. Which accounting focuses on environmental and social impact? A) Sustainability Accounting B) Tax Accounting C) Financial Accounting D) Payroll Accounting', 'A'),
('72. What is CSR? A) Company Sales Revenue B) Corporate Social Responsibility C) Certified Strategic Reporting D) Corporate Sales Ratio', 'B'),
('73. Which type of audit is performed by company employees? A) External Audit B) Internal Audit C) Government Audit D) Tax Audit', 'B'),
('74. Which statement shows revenues and expenses? A) Balance Sheet B) Income Statement C) Cash Flow Statement D) Budget Sheet', 'B'),
('75. What is operating income? A) Sales revenue B) Profit from core operations C) Gross profit D) Net worth', 'B'),
('76. Which term means owners residual interest? A) Liability B) Equity C) Revenue D) Expense', 'B'),
('77. What is financial leverage? A) Use of debt financing B) Revenue increase C) Inventory reduction D) Tax planning', 'A'),
('78. Which financing involves issuing shares? A) Debt Financing B) Equity Financing C) Lease Financing D) Vendor Financing', 'B'),
('79. Which financing involves borrowing funds? A) Equity Financing B) Debt Financing C) Stock Financing D) Revenue Financing', 'B'),
('80. What is a bond? A) Ownership security B) Debt security C) Inventory asset D) Insurance contract', 'B'),
('81. What is dividend? A) Loan repayment B) Shareholder profit distribution C) Employee bonus D) Tax refund', 'B'),
('82. Which analysis reviews financial statements? A) Financial Statement Analysis B) SWOT Analysis C) Cost Analysis D) Gap Analysis', 'A'),
('83. What is standard costing? A) Using estimated predetermined costs B) Actual costing only C) Tax calculation D) Inventory valuation', 'A'),
('84. Which variance relates to labor cost differences? A) Sales Variance B) Material Variance C) Labor Variance D) Overhead Variance', 'C'),
('85. Which variance relates to raw material cost differences? A) Material Variance B) Labor Variance C) Sales Variance D) Profit Variance', 'A'),
('86. Which variance relates to indirect cost differences? A) Sales Variance B) Overhead Variance C) Labor Variance D) Material Variance', 'B'),
('87. What is direct labor cost? A) Indirect wage B) Employee wages directly tied to production C) Administrative salary D) Marketing expense', 'B'),
('88. Which process identifies and manages risks? A) Risk Management B) Forecasting C) Budgeting D) Auditing', 'A'),
('89. What is strategic planning? A) Daily operations B) Long-term organizational planning C) Inventory control D) Payroll process', 'B'),
('90. What is operational planning? A) Short-term detailed planning B) Marketing campaign C) Audit review D) Tax filing', 'A'),
('91. Which term refers to analyzing data for insights? A) Data Analytics B) Cost Accounting C) Benchmarking D) Hedging', 'A'),
('92. What is business intelligence? A) Employee knowledge B) Technology-driven business analysis C) Market risk D) Cost control', 'B'),
('93. Which manufacturing approach reduces waste? A) Lean Manufacturing B) Standard Costing C) FIFO D) Absorption Costing', 'A'),
('94. Which report helps managers monitor performance? A) KPI Report B) Tax Return C) Audit Certificate D) Bank Statement', 'A'),
('95. What is economic value added? A) Revenue increase B) Profit after cost of capital C) Gross profit D) Operating income', 'B'),
('96. Which ratio measures efficiency in using assets? A) Asset Turnover Ratio B) Debt Ratio C) Current Ratio D) Gross Margin', 'A'),
('97. What is transfer pricing? A) Bank transfer fee B) Pricing between divisions C) Shipping charge D) Inventory cost', 'B'),
('98. Which center is responsible for revenues and costs? A) Cost Center B) Revenue Center C) Profit Center D) Investment Center', 'C'),
('99. Which center is evaluated on return on investment? A) Cost Center B) Investment Center C) Revenue Center D) Expense Center', 'B'),
('100. What is responsibility accounting? A) Accounting based on areas of responsibility B) Tax accounting C) Financial reporting D) Payroll processing', 'A');
select * from exam_questions;